### ISSUE TITLE
XenBase GPI file errors

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-releases#116]
I am QCing the GPI files for Xenbase, and there are 3 important issues: 

1. In the cross-references, UniProKB is spelled incorrectly (UniprotKB, should be capital P = **UniProtKB**)
2. There are about 25,000 entities (out of a total of 68,000) that have no mappings. Is this correct? 
3. All entities are type = gene. Can you be more specific, for example, protein-coding genes? all all entities protein-coding genes? 
4. At some point in the future it'd be great if you could produce a GPI 2.0. 

Files for QC are here: https://drive.google.com/drive/folders/1fSHzAf6jOPgE4TN8vAYRdI_gFTRDPMJz

Thanks, Pascale

**Comment by malcolmfisher103** [comment]
1. The UniProtKB fix will be actioned shortly.
2.  I'll look into this, I suspect that we are exporting some genes that we do not have supporting evidence for but were created because they were in the other species. We have unified gene pages for both our species so when the genepage is curated placeholder entities are created for both species, it looks like some of these placeholders are being exported in the GPI.
3. We should have the information for a more granular object_type/SO term. 
4. We have actually been producing a GPIv2 version for a while, but we are in the middle of updating it to accommodate the recent changes to  column 9. This is a good opportunity to make sure all the issues you raised for the v1.1 GPI are applied in both contexts.

**Comment by pgaudet** [comment]
Great ! Let me know when a new file is ready.

**Comment by pgaudet** [comment]
Hi @malcolmfisher103 

Looking at the XenBase GPI file from 09-04-2025 (which I think is the most recent one),  the "UniprotKB" spelling issue is still not fixed. Any idea when this will be available ? 

Also, is the GPI2.0 available yet ? 

Thanks, Pascale

**Comment by malcolmfisher103** [comment]
Thanks for following up on this @pgaudet it seems that a couple of months ago the endpoint for the GPI in the xenbase.yaml was changed, it does not reflect our current GPI which should have the corrected UniProtKB curies, although I don't think the more granular SO terms have been applied yet. I have put in a Pull request ([#2516](https://github.com/geneontology/go-site/pull/2516)) to update the yaml. I will follow up with our dev team on the GPI2.0 and the SO terms.

**Comment by pgaudet** [comment]
Hi @malcolmfisher103 
Thanks for the quick reply!

In the new file from 28-05-2025  that I downloaded in the new URL (https://download.xenbase.org/xenbase/GenePageReports/xenbase.gpi.gz)  I still see the problem: 

Xenbase	XB-GENE-478084	tbx1	T-box 1	cafs|cthm|dgcr|dorv|tbx1-a|tbx1-b|tbx1c|vcfs|xtbx1	gene	taxon:8364		NCBI_Gene:619587|**UniprotKB**:Q3SA49	


Did I not get the correct file? 

Thanks, Pascale

**Comment by malcolmfisher103** [comment]
Hi Pascale,

Sorry that is my fault, I saw after I replied earlier that the prefixes had been changed in the Headers but not in the actual file content, I updated the script but it hasn't been re-run yet.

Apologies,

Malcolm

-------------------------

Malcolm Fisher, PhD

Xenbase Senior Biocurator

Cincinnati Children’s Hospital Medical Center

Division of Developmental Biology

3333 Burnet Avenue, Cincinnati,

Ohio 45229-3026

Tel:(513) 803 5379



________________________________

**Comment by pgaudet** [comment]
Thanks for the explanation! I'll check later. 

Best, 

Pascale

**Comment by malcolmfisher103** [comment]
The file at the new URL should have the correct prefixes now, sorry for the delay.

**Comment by pgaudet** [comment]
Looks great, thanks @malcolmfisher103 !

**Comment by pgaudet** [comment]
Hi @malcolmfisher103 

Unfortunately we encountered once again the non-ascii character issue, for XB-GENE-487309

Xenbase	XB-GENE-487309	gdf3	growth differentiation factor 3	derriere|**derri?e|**gdf1|gdf-3|vgr-2|vgr2	gene	taxon:8364		NCBI_Gene:493288|UniProtKB:Q66KL4|UniProtKB:A0A803JTG3	

Xenbase	XB-GENE-876260	mnat1	MNAT1, CDK activating kinase assembly factor	MAT1|menage ? trois	gene	taxon:8364		NCBI_Gene:549892|UniProtKB:Q28H72	

Xenbase	XB-GENE-876260	mnat1	MNAT1, CDK activating kinase assembly factor	MAT1|menage ? trois	gene	taxon:8364		NCBI_Gene:549892|UniProtKB:Q28H72	

Xenbase	XB-GENE-17338125	mnat1.S	MNAT1, CDK activating kinase assembly factor S homeolog	MAT1|menage ? trois	gene	taxon:8355		NCBI_Gene:108700473|	


I am not sure this list is exhaustive. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also: [in February ](https://github.com/geneontology/go-releases/issues/116#issuecomment-2657474371)you mentioned that XenBase could (1) produce a GPI 2.0 and (2) use more granular SO/object IDs. Do you know when this might be available ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also, would it be possible to provide 2 GPI files for laveis and tropicalis ?

**Comment by malcolmfisher103** [comment]
@pgaudet The file should be updated now with the proper encoding. I'll follow up on the other issues with our development team, separate species specific files should be simple enough.

**Comment by pgaudet** [comment]
Hi @malcolmfisher103 

In the Xenbase file from 2025-10-25 , there is still that illegal character: **derriére** and **menage à trois**

* Xenbase	XB-GENE-487309	gdf3	growth differentiation factor 3	derriere|derriére|gdf1|gdf-3|vgr-2|vgr2	gene	taxon:8364		NCBI_Gene:493288|UniProtKB:Q66KL4|UniProtKB:A0A803JTG3	
* Xenbase	XB-GENE-876260	mnat1	MNAT1, CDK activating kinase assembly factor	MAT1|menage à trois	gene	taxon:8364		NCBI_Gene:549892|UniProtKB:Q28H72	
* Xenbase	XB-GENE-876269	mnat1.L	MNAT1, CDK activating kinase assembly factor L homeolog	MAT1|menage à trois	gene	taxon:8355		NCBI_Gene:380053|UniProtKB:P51951|UniProtKB:A0A974C8D4	

Can this be permanently fixed? 

Thanks, Pascale

**Comment by malcolmfisher103** [comment]
Hi Pascale,

I think we are there, we have split up the GPIs by species and updated them to the 2.0 spec. This should include the fixes for the noncompliant characters. 

The new species specific links for the updated format are ...

X. tropicalis - https://download.xenbase.org/xenbase/GenePageReports/GOBySpecies/xenbase_v2.0.xtrop.only.gpi.gz
X, laevis - https://download.xenbase.org/xenbase/GenePageReports/GOBySpecies/xenbase_v2.0.xlaev.only.gpi.gz

Please let us know if you find any other issues. 

If I update this in the xenbase.yaml how should the separate species GPIs be handled? I have a version below but I'm not sure if anything else, such as 'dataset' needs to be species specific.

```
id: xenbase_xtro.gpi
    label: "Xenbase X. tropicalis gpi file"
    description: "gpi file for X. tropicalis from Xenbase"
    type: gpi
    dataset: xenbase
    submitter: xenbase
    compression: gzip
    source: https://download.xenbase.org/xenbase/GenePageReports/GOBySpecies/xenbase_v2.0.xtrop.only.gpi.gz
    entity_type:
    status: active
    species_code: Xtro
    taxa:
      - NCBITaxon:8364
-
id: xenbase_xlae.gpi
    label: "Xenbase X. laevis gpi file"
    description: "gpi file for X. laevis from Xenbase"
    type: gpi
    dataset: xenbase
    submitter: xenbase
    compression: gzip
    source: https://download.xenbase.org/xenbase/GenePageReports/GOBySpecies/xenbase_v2.0.xlaev.only.gpi.gz
    entity_type:
    status: active
    species_code: Xlae
    taxa:
      - NCBITaxon:8355
```
